package com.lello.dualsimscheduler.automation

enum class AutomationState {
    IDLE,
    START_GO_PRIVATE,
    OPENING_SIM_SETTINGS_FOR_DISABLE,
    DISABLING_WORK_SIM,
    WAITING_WORK_SIM_DISABLED,
    OPENING_USER_SWITCHER_FOR_PRIVATE,
    SWITCHING_TO_PRIVATE,
    ARRIVED_PRIVATE,
    START_GO_WORK,
    OPENING_USER_SWITCHER_FOR_WORK,
    SWITCHING_TO_WORK,
    ARRIVED_WORK,
    OPENING_SIM_SETTINGS_FOR_ENABLE,
    ENABLING_WORK_SIM,
    WAITING_WORK_SIM_ENABLED,
    COMPLETED,
    ERROR,
}
